extends:
  - airbnb
  - airbnb/hooks
  - plugin:react/recommended
  - plugin:jsx-a11y/recommended
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - jsx-a11y
rules:
  object-curly-newline: 0
  no-plusplus:
    - 1
    - allowForLoopAfterthoughts: true
  no-use-before-define:
    - 1
    - { 'functions': false, 'classes': false }
  comma-dangle: 0
  jsx-a11y/anchor-is-valid: 0
  react/no-array-index-key: 0
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
        - .js
        - .jsx
  react/jsx-wrap-multilines: 0
  react/jsx-props-no-spreading: 0
